yandex:
  storage:
    access-key: ${YANDEX_ACCESS_KEY}
    secret-key: ${YANDEX_SECRET_KEY}
    bucket-name: ${YANDEX_BUCKET_NAME}
    endpoint: ${YANDEX_ENDPOINT:https://storage.yandexcloud.net}
    region: ${YANDEX_REGION:ru-central1}

file:
  upload:
    max-size: 10485760
    max-files: 5

logging:
  level:
    ru.melulingerie: INFO
    software.amazon.awssdk: WARN

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
      enabled: true

  datasource:
    url: jdbc:postgresql://localhost:5432/melu_lingerie_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true