spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Backend Service Route
        - id: backend-service
          uri: ${BACKEND_URL:http://51.250.69.176:8080}
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
        - AddResponseHeader=X-Frame-Options, DENY
        - AddResponseHeader=X-Content-Type-Options, nosniff
        - AddResponseHeader=X-XSS-Protection, 1; mode=block

      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:4200"
              - "http://localhost:8080"
              - "http://51.250.69.176"
              - "https://51.250.69.176"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600

# Server Configuration
server:
  port: 8765
  shutdown: graceful

# Management & Actuator
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
      base-path: /actuator
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true

# Logging Configuration
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web.reactive: INFO
    reactor.netty: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"