package ru.mellingerie.api.common;

public enum ErrorCode {
    MISSING_USER_ID_HEADER,
    VALIDATION_FAILED,
    WISHLIST_ITEM_DUPLICATE,
    INVALID_ID,
    WISHLIST_ITEM_NOT_FOUND,
    WISHLIST_CAPACITY_EXCEEDED,
    MEDIA_PROCESSING_FAILED,
    INTERNAL_ERROR,
}


