spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

yandex:
  storage:
    access-key: ${YANDEX_ACCESS_KEY}
    secret-key: ${YANDEX_SECRET_KEY}
    bucket-name: ${YANDEX_BUCKET_NAME}
    endpoint: ${YANDEX_ENDPOINT:https://storage.yandexcloud.net}
    region: ${YANDEX_REGION:ru-central1}

file:
  upload:
    max-size: 52428800 # 50MB
    allowed-image-types: image/jpeg,image/png,image/gif,image/webp,image/bmp
    allowed-image-extensions: .jpg,.jpeg,.png,.gif,.webp,.bmp
    allowed-video-types: video/mp4,video/webm,video/ogg,video/quicktime
    allowed-video-extensions: .mp4,.webm,.ogg,.mov


logging:
  level:
    ru.melulingerie: INFO
    software.amazon.awssdk: WARN