yandex:
  storage:
    access-key: AKIA_EXAMPLE_ACCESS_KEY
    secret-key: example_secret_key_12345678901234567890
    bucket-name: test-bucket
    endpoint: https://storage.yandexcloud.net
    region: ru-central1

file:
  upload:
    max-size: 10485760 # 10MB
    allowed-image-types: image/jpeg,image/png,image/gif,image/webp,image/bmp
    allowed-image-extensions: .jpg,.jpeg,.png,.gif,.webp,.bmp
    allowed-video-types: video/mp4,video/webm,video/ogg,video/quicktime
    allowed-video-extensions: .mp4,.webm,.ogg,.mov


logging:
  level:
    ru.melulingerie: INFO
    software.amazon.awssdk: WARN